import { readFile, writeFile, mkdir, cp } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const root = fileURLToPath(new URL('..', import.meta.url));
const out = path.join(root, 'dist');
await mkdir(out, { recursive: true });
let html = await readFile(path.join(root, 'index.html'), 'utf8');
const css = await readFile(path.join(root, 'src/style.css'), 'utf8');
const sim = await readFile(path.join(root, 'src/simulation.js'), 'utf8');
const game = await readFile(path.join(root, 'src/game.js'), 'utf8');
const terrain = (await readFile(path.join(root, 'assets/terrain.png'))).toString('base64');
const sprites = (await readFile(path.join(root, 'assets/sprites.png'))).toString('base64');
html = html.replace('<link rel="stylesheet" href="src/style.css">', () => `<style>${css}</style>`);
html = html.replace('<script src="src/simulation.js"></script><script src="src/game.js"></script>', () => `<script>window.GULF_ASSETS=${JSON.stringify({ terrain: `data:image/png;base64,${terrain}`, sprites: `data:image/png;base64,${sprites}` })};</script><script>${sim}</script><script>${game}</script>`);
await writeFile(path.join(out, 'index.html'), html);
await writeFile(path.join(out, 'Desert-Strike.html'), html);
await writeFile(path.join(out, '.nojekyll'), '');
await cp(path.join(root, 'LICENSE'), path.join(out, 'LICENSE'));
console.log(`Built self-contained game: ${path.join(out, 'Desert-Strike.html')} (${(Buffer.byteLength(html) / 1024 / 1024).toFixed(1)} MB)`);
